version: "3.7"
services:
  smsc-simulator:
    restart: unless-stopped
    image: damiangallo/smsc-simulator:latest
    environment:
      - PORT=2775
      - SYSTEM_ID=admin
      - PASSWORD=secret
    ports:
      - 2775:2775